builds:
  - binary: mubeng
    main: cmd/mubeng/main.go
    ldflags:
      - -s -w -X github.com/tikhobrae/H3Pr0xy/tree/main/src/GoScanner/common.Version=v{{.Version}}
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - 386
      - arm
      - arm64
  
archives:
  - id: binary
    format: binary